### ISSUE TITLE
Vim(helptags):E154: Duplicate tag ":Ag" in file ...fzf-vim.txt

### ISSUE THREAD

**Issue by LEUNGUU** [PegasusWang/vim-config#3]
I am using nvim(v0.4.3).
when i run make in .config/nvim directory, it occurs:
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag ":Ag" in file /home/anoy/.cache/vim/dein/.cache/init.vim/.dein/doc/fzf-vim.txt
[dein] function dein#update[1]..dein#install#_update[38]..<SNR>112_update_loop[5]..<SNR>112_install_async[9]..<SNR>112_done[9]..dein#install#_recache_runtimepath[19]..<SNR>112_helptags, line 12

Please help.

**Comment by PegasusWang** [comment]
Updated. remove duplicated plugin. Please retry.

":Ag" command ag.vim conflict with fzf.vim. I removed ag.vim and use fzf.

**Comment by LEUNGUU** [comment]
Thanks
