### ISSUE TITLE
config/local.vim 还是 .config/local.vim

### ISSUE THREAD

**Issue by Adolf-L** [PegasusWang/vim-config#4]
![image](https://user-images.githubusercontent.com/10137107/83434970-07a78b80-a46e-11ea-9cc6-4aa3c0f5896c.png)
~ 路径下面有一个 .config 文件夹。 这里的 config 是不是指的 .config?

**Comment by Adolf-L** [comment]
～/config  folder

**Comment by PegasusWang** [comment]
当前项目下的 config/local.vim
