### ISSUE TITLE
LspInstallServer cmd can't find

### ISSUE THREAD

**Issue by Adolf-L** [PegasusWang/vim-config#5]
![image](https://user-images.githubusercontent.com/10137107/83498234-32392900-a4ee-11ea-9026-5137fc8b7e36.png)
好像，我的配置基本安装好了，但是 LSP 启动命令找不到

**Comment by PegasusWang** [comment]
这里用的是 coc.nvim，如果直接安装完成的话就可以了，不用执行这个命令。文档暂时和原项目有一些区别

**Comment by Adolf-L** [comment]
嗯

**Comment by atmoxao** [comment]
我也出现啦 ，Mac上面可以 arch上就不行 
然后导致 补全不能用
```bash
not an editor command :LspInstallServer 
```
